

/**
 * getArmorByName
 *
 * @param  {string} name of armor
 * @returns {object} armor
 */
function getArmorByName(name = '') {
  return armor.filter(armor => armor.name === name)[0];
}

export { getArmorByName };

const armor = [
  {
    name: "Ring of Fury",
    description: 'It feels tingly!',
    ilvl: 1,
    armor: 14,
    strength: 14,
    cost: 13,
    sellPrice: 26,
    slot: 'ring',
    type: 'armor',
    skillType: 'mail',
    durability: 55,
    repairCost: 44,
    disenchant: 'no',
    icon: 'item-29',
    color: 'purple',
    droppedBy: '',
    levelRequirement: 1
  },
  {
    name: "Recruit's Vest",
    description: "Obviously used before.",
    ilvl: 1,
    armor: 7,
    cost: 13,
    sellPrice: 2,
    slot: 'chest',
    type: 'armor',
    skillType: 'mail',
    durability: 55,
    repairCost: 44,
    disenchant: 'no',
    icon: 'item-04',
    color: 'green',
    droppedBy: '',
    levelRequirement: 1
  },
  {
    name: "Recruit's Pants",
    description: "Not very nice.",
    ilvl: 1,
    armor: 6,
    cost: 13,
    sellPrice: 2,
    slot: 'legs',
    type: 'armor',
    skillType: 'mail',
    durability: 40,
    repairCost: 32,
    disenchant: 'no',
    icon: 'item-02',
    color: 'green',
    droppedBy: '',
    levelRequirement: 1
  },
  {
    name: "Recruit's Boots",
    description: "What's this stain?",
    ilvl: 1,
    armor: 5,
    cost: 9,
    sellPrice: 1,
    slot: 'feet',
    type: 'armor',
    skillType: 'mail',
    durability: 25,
    repairCost: 20,
    disenchant: 'no',
    icon: 'item-24',
    color: 'blue',
    droppedBy: '',
    levelRequirement: 1
  },
  {
    name: "Footpad's Vest",
    description: "What's a 'Footpad'?",
    ilvl: 1,
    armor: 3,
    cost: 13,
    sellPrice: 2,
    slot: 'chest',
    type: 'armor',
    skillType: 'leather',
    durability: 55,
    repairCost: 44,
    disenchant: 'no',
    icon: 'item-02',
    color: 'yellow',
    droppedBy: '',
    levelRequirement: 1
  },
  {
    name: "Footpad's Pants",
    description: "Smells leathery.",
    ilvl: 1,
    armor: 3,
    cost: 13,
    sellPrice: 2,
    slot: 'legs',
    type: 'armor',
    skillType: 'leather',
    durability: 40,
    repairCost: 32,
    disenchant: 'no',
    icon: 'item-05',
    color: 'green',
    droppedBy: '',
    levelRequirement: 1
  },
  {
    name: "Footpad's Shoes",
    description: "A little too tight.",
    ilvl: 1,
    armor: 2,
    cost: 9,
    sellPrice: 1,
    slot: 'feet',
    type: 'armor',
    skillType: 'leather',
    durability: 25,
    repairCost: 20,
    disenchant: 'no',
    icon: 'item-02',
    color: 'green',
    droppedBy: '',
    levelRequirement: 1
  },
  {
    name: "Apprentice's Robe",
    description: "Like a sack.",
    ilvl: 1,
    armor: 2,
    cost: 13,
    sellPrice: 2,
    slot: 'chest',
    type: 'armor',
    skillType: 'cloth',
    durability: 55,
    repairCost: 44,
    disenchant: 'no',
    icon: 'item-05',
    color: 'red',
    droppedBy: '',
    levelRequirement: 1
  },
  {
    name: "Apprentice's Pants",
    description: "Shabby and worn.",
    ilvl: 1,
    armor: 2,
    cost: 13,
    sellPrice: 2,
    slot: 'legs',
    type: 'armor',
    skillType: 'cloth',
    durability: 40,
    repairCost: 32,
    disenchant: 'no',
    icon: 'item-03',
    color: 'blue',
    droppedBy: '',
    levelRequirement: 1
  },
  {
    name: "Apprentice's Boots",
    description: "More like socks.",
    ilvl: 1,
    armor: 1,
    cost: 10,
    sellPrice: 1,
    slot: 'feet',
    type: 'armor',
    skillType: 'cloth',
    durability: 25,
    repairCost: 20,
    disenchant: 'no',
    icon: 'item-01',
    color: 'purple',
    droppedBy: '',
    levelRequirement: 1
  },
]
